### ISSUE TITLE
Current state?

### ISSUE THREAD

**Issue by TomasVotruba** [adawolfa/bower-loader#1]
What's the current state of this package? Do you still use is or have you find better solution?

**Comment by adawolfa** [comment]
I'll check whether everything still works and fix it in a week or so (and I'll update dependency of WebLoader to 2.3).

**Comment by TomasVotruba** [comment]
Thanks for reply. How do you manage assets dependencies at the moment?

**Comment by adawolfa** [comment]
Well using `.bowerrc` I point packages directory somewhere into `wwwDir` and the required URL filtering resolves the CssUrlsFilter (which is now deprecated?).
